### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by jacob-bw** [Jason-Lee-Scott/CandyMarket#2]
## User Story
As a developer I want an ERD so that I am to be able to ensure that I'm structuring data correctly

## Dev Notes
* the ERD should have collections for candy, users, and a join table for candy owned by users called UsersCandy
* the `Candy` Collection needs to contain fields for `id`, `name`, `manufacturer`, `flavorCategory`, and `expirationDate`
* the 'User' collection needs fields for `id`, `fullName`, and `emailAddress`

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/82395243-b9779e80-9a10-11ea-8ba3-e06bd41e8432.png)
