### ISSUE TITLE
Setup project in visual studio

### ISSUE THREAD

**Issue by kelsey-21** [Jason-Lee-Scott/CandyMarket#5]
## User Story
As a developer, I want my folders and files setup appropriately in visual studio so that my API and SQL calls work correctly.

## AC
* Delete all references to Weather Forecast
* Create folders for `DataAccess`, `Models`, and `Controllers`
* In the `DataAccess` folder - create classes called `CandyRepository` and `UserRepository`
* In the `Models` folder - create classes called `User` and `Candy` with properties that match the columns from the ERD
* In the `Controllers` folder - create `CandyController` and `UserController`

## Dev Notes
* `UserController` path should be `api/user`
* `CandyController` path should be `api/candy`

**Comment by jacob-bw** [comment]
@kelseycreel this ticket is a thing of beauty

**Comment by jacob-bw** [comment]
🥇
